image:
- Visual Studio 2017
- Ubuntu

stack: python 3

environment:
  PY_DIR: C:\Python37-x64

init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:

  # We need wheel installed to build wheels
  - pip install wheel --no-warn-script-location"
  - pip install numpy
  - pip install -ve .

build: off

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  - "%PYTHON%\\python.exe setup.py build_ext build_py install"
  - cd examples
  - python single_layer.py
  - cd ..

